on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (if needed)
        run: rustup update

      - name: Build release
        run: cargo test --release
        env:
          RUST_BACKTRACE: full

      - name: Build package
        if: matrix.os == 'ubuntu-latest'
        run: tar --no-same-owner -czf jlo-linux.tar.gz jlo-init.sh -C target/release jlo-bin

      - name: Build package
        if: matrix.os == 'macos-latest'
        run: tar --no-same-owner -czf jlo-macos.tar.gz jlo-init.sh -C target/release jlo-bin

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test
          files: jlo-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
